version: '2'

services:
    web:
        build:
            context: ./images/bitbucket
            args:
                - BITBUCKET_VERSION=${BITBUCKET_VERSION}
        image: ianharrier/bitbucket:${BITBUCKET_VERSION}
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - ${WEB_PORT}:7990
            - ${WEB_SSH_PORT}:7999
        environment:
            - PROXY_HOSTNAME=${WEB_PROXY_HOSTNAME}
            - PROXY_PORT=${WEB_PROXY_PORT}
            - PROXY_SCHEME=${WEB_PROXY_SCHEME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/web/data:/var/atlassian/application-data/bitbucket
    db:
        image: postgres:9.6-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        volumes:
            - ./volumes/db/data:/var/lib/postgresql/data
    backup:
        build:
            context: ./images/backup
            args:
                - GLIBC_VERSION=2.25-r0
                - COMPOSE_VERSION=1.13.0
        image: ianharrier/bitbucket-backup:1.0.4
        restart: unless-stopped
        environment:
            - OPERATION=${BACKUP_OPERATION}
            - CRON_EXP=${BACKUP_CRON_EXP}
            - RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - BITBUCKET_USERNAME=${BACKUP_BITBUCKET_USERNAME}
            - BITBUCKET_PASSWORD=${BACKUP_BITBUCKET_PASSWORD}
        volumes:
            - ./:${PWD}
            - /var/run/docker.sock:/var/run/docker.sock
