version: '2'

services:
    web:
        build:
            context: ./images/bitbucket
            args:
                - BITBUCKET_VERSION=${BITBUCKET_VERSION}
        image: ianharrier/bitbucket:${BITBUCKET_VERSION}
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - ${WEB_PORT}:7990
            - ${WEB_SSH_PORT}:7999
        environment:
            - PROXY_HOSTNAME=${WEB_PROXY_HOSTNAME}
            - PROXY_PORT=${WEB_PROXY_PORT}
            - PROXY_SCHEME=${WEB_PROXY_SCHEME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/web/data:/var/atlassian/application-data/bitbucket:z
    db:
        image: postgres:9.6-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        volumes:
            - ./volumes/db/data:/var/lib/postgresql/data:z
    cron:
        build:
            context: ./images/cron
        image: ianharrier/bitbucket-cron:1.1.1
        restart: unless-stopped
        environment:
            - BACKUP_OPERATION=${BACKUP_OPERATION}
            - BACKUP_CRON_EXP=${BACKUP_CRON_EXP}
            - BACKUP_RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - TIMEZONE=${TIMEZONE}
            - POSTGRES_DB=${DB_POSTGRES_DB}
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
            - BITBUCKET_USERNAME=${BACKUP_BITBUCKET_USERNAME}
            - BITBUCKET_PASSWORD=${BACKUP_BITBUCKET_PASSWORD}
        volumes:
            - ./:${PWD}:z
